name: Docker build
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
  schedule:
    - cron: "0 11 * * *"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Clears preinstalled toolchains, avoiding GitHub runner disk space issues
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Test Space ROS
        id: build
        run: |
          docker buildx build \
            --target export-build-test \
            --build-arg IMAGE_VARIANT=dev \
            --output type=local,dest=log/build_results_archives \
            .
          echo "archivename=$(basename log/build_results_archives/build_results_*.tar.bz2)" >> $GITHUB_ENV

      - name: Upload build results archive
        uses: actions/upload-artifact@v7
        with:
          name: ${{env.archivename}}
          path: log/build_results_archives/${{env.archivename}}
          if-no-files-found: error
          compression-level: 0

  space-ros-main-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "${{ github.head_ref || github.ref_name }}"
      VCS_REF: ${{ github.sha }}
      GHCR_IMAGE_NAME: "ghcr.io/space-ros/space-ros"
      DOCKER_HUB_USERNAME: osrfbot
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_RW_TOKEN }}
      DOCKER_HUB_IMAGE_NAME: "osrf/space-ros"

    steps:
      # Clears preinstalled toolchains, avoiding GitHub runner disk space issues
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout
        uses: actions/checkout@v7

      - name: Sanitize image tag
        run: echo "IMAGE_TAG=${IMAGE_TAG//\//-}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build spaceros image without pushing
        run: |
          docker buildx build \
            --target image \
            --build-arg IMAGE_VARIANT=main \
            --build-arg VCS_REF="${VCS_REF}" \
            --tag "$DOCKER_HUB_IMAGE_NAME:$IMAGE_TAG" \
            --load \
            .

      # Login and push the main builds to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the main spaceros image to GHCR
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag "$DOCKER_HUB_IMAGE_NAME:$IMAGE_TAG" "$GHCR_IMAGE_NAME:$IMAGE_TAG"
          docker push "$GHCR_IMAGE_NAME:$IMAGE_TAG"

      # Push both tagged releases and the latest main builds to Dockerhub
      - name: Push spaceros images to Dockerhub
        if: ${{ github.ref_type == 'tag' || github.ref_name == 'main' }}
        run: |
          # We must login using the password and not the action, as the action only supports tokens.
          echo "$DOCKER_HUB_TOKEN" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
          docker push "$DOCKER_HUB_IMAGE_NAME:$IMAGE_TAG"

      # Any tagged image should also be marked as "latest"
      - name: Push spaceros latest images to Dockerhub
        if: ${{ github.ref_type == 'tag' }}
        run: |
          # We must login using the password and not the action, as the action only supports tokens.
          echo "$DOCKER_HUB_TOKEN" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
          docker tag "$DOCKER_HUB_IMAGE_NAME:$IMAGE_TAG" "$DOCKER_HUB_IMAGE_NAME:latest"
          docker push "$DOCKER_HUB_IMAGE_NAME:latest"

  space-ros-dev-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "${{ github.head_ref || github.ref_name }}-dev"
      VCS_REF: ${{ github.sha }}
      GHCR_IMAGE_NAME: "ghcr.io/space-ros/space-ros"
      DOCKER_HUB_USERNAME: osrfbot
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_RW_TOKEN }}
      DOCKER_HUB_IMAGE_NAME: "osrf/space-ros"

    steps:
      # Clears preinstalled toolchains, avoiding GitHub runner disk space issues
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout
        uses: actions/checkout@v7

      - name: Sanitize image tag
        run: echo "IMAGE_TAG=${IMAGE_TAG//\//-}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build spaceros dev image without pushing
        run: |
          docker buildx build \
            --target image \
            --build-arg IMAGE_VARIANT=dev \
            --build-arg VCS_REF="${VCS_REF}" \
            --tag "$DOCKER_HUB_IMAGE_NAME:$IMAGE_TAG" \
            --load \
            .

      # Only push the main dev builds to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the dev spaceros image to GHCR
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag "$DOCKER_HUB_IMAGE_NAME:$IMAGE_TAG" "$GHCR_IMAGE_NAME:$IMAGE_TAG"
          docker push "$GHCR_IMAGE_NAME:$IMAGE_TAG"

      # Push both tagged releases and the main dev builds to Dockerhub
      - name: Push spaceros images to Dockerhub
        if: ${{ github.ref_type == 'tag' || github.ref_name == 'main' }}
        run: |
          # We must login using the password and not the action, as the action only supports tokens.
          echo "$DOCKER_HUB_TOKEN" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
          docker push "$DOCKER_HUB_IMAGE_NAME:$IMAGE_TAG"
